# Notes
recently_edited = None

colors = dict()
colors["Red"] = "red"
colors["Orange"] = "orange"
colors["Yellow"] = "gold"
colors["Green"] = "forest green"
colors["Blue"] = "royalblue3"
colors["Purple"] = "darkorchid3"
colors["Pink"] = "deeppink2"

sizes = dict()
sizes["Title 1"] = 28
sizes["Title 2"] = 24
sizes["Title 3"] = 20
sizes["Text"] = 14

# Represents different kinds of fonts that have been generated by style window
generated_fonts = list()

curr_font = ('calibre', 14, 'normal')
curr_color = "None"

# Dictionary
hanzi = dict()

results_table = None
results_canvas = None

# Color mode
mode = 'D'

